nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['Link', 'Authorization']  # Specify headers you want to expose
        max_age: 0
    paths:
        '^/': null  # Allow all paths