version: '3.7'
services:
    mysql:
        build: .docker/mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PORT=$MYSQL_PORT
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql:rw
    mongo:
        build: ./.docker/mongo
        ports:
            - "27017:27017"
        volumes:
            - ./.docker/mongo/data:/data/db:rw
            - ./tests/etc/_data/mongo:/testing-data:rw
    web_api:
        build:
            context: ./.docker/php
            args:
                - uid=1000
                - gid=1000
            target: web_api
        volumes:
            - ./:/var/www/app:cached
        depends_on:
            - mysql
            - mongo
            - rabbit
    events_consumer:
        build:
            context: ./.docker/php
            target: events_consumer
        volumes:
            - ./:/var/www/app:cached
        depends_on:
            - web_api
    nginx:
        build: ./.docker/nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app:cached
        depends_on:
            - web_api
    rabbit:
        image: rabbitmq:3.8-management
        hostname: rabbitmq
        ports:
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=$RABBIT_USER
            - RABBITMQ_DEFAULT_PASS=$RABBIT_PASSWORD
