services:
    mysql:
        build: .docker/mysql
        container_name: mcq_mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PORT=$MYSQL_PORT
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql:rw

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: mcq_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
        ports:
            - "8780:80"
        depends_on:
            - mysql

    mongo:
        build: ./.docker/mongo
        container_name: mcq_mongo
        ports:
            - "27017:27017"
        volumes:
            - ./.docker/mongo/data:/data/db:rw
            - ./tests/etc/_data/mongo:/testing-data:rw

    web_api:
        build:
            context: ./.docker/php
            args:
                - uid=1000
                - gid=1000
            target: web_api
        container_name: web_api
        volumes:
            - ./:/var/www/app:cached
        depends_on:
            - mysql
            - mongo
            - rabbit

    events_consumer:
        build:
            context: ./.docker/php
            target: events_consumer
        container_name: events_consumer
        volumes:
            - ./:/var/www/app:cached
        depends_on:
            - web_api

    nginx:
        build: ./.docker/nginx
        container_name: mcq_nginx
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www/app:cached
        depends_on:
            - web_api

    rabbit:
        image: rabbitmq:3.8-management
        container_name: mcq_rabbit
        hostname: rabbitmq
        ports:
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=$RABBIT_USER
            - RABBITMQ_DEFAULT_PASS=$RABBIT_PASSWORD

    ###> symfony/mercure-bundle ###
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            # Uncomment the following line to disable HTTPS,
            SERVER_NAME: ':3000'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins *
        # Comment the following line to disable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
        healthcheck:
            test: ["CMD", "curl", "-f", "https://localhost/healthz"]
            timeout: 5s
            retries: 5
            start_period: 60s
        ports:
            - "3000:3000"
        volumes:
            - mercure_data:/data
            - mercure_config:/config
    ###< symfony/mercure-bundle ###

    portainer:
        image: portainer/portainer-ce:latest
        container_name: mcq_portainer
        ports:
            - "9943:9443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    mercure_data:
    mercure_config: