version: '3.7'
services:
    mysql:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PORT=$MYSQL_PORT
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql:rw
    mongo:
        build: ./.docker/mongo
        ports:
            - "27017:27017"
        volumes:
            - ./.docker/mongo/data:/data/db:rw
            - ./tests/etc/_data/mongo:/testing-data:rw
    php:
        build: ./.docker/php
        volumes:
            - ./:/var/www/app:cached
        links:
            - mysql
            - mongo
    nginx:
        build: ./.docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./:/var/www/app:cached
