Taranto\ListMaker\Domain\Model\Common\DomainEvent:
    discriminator_map:
        type_property: event_type
        mapping:
            # Board
            board-created: 'Taranto\ListMaker\Domain\Model\Board\Event\BoardCreated'
            board-title-changed: 'Taranto\ListMaker\Domain\Model\Board\Event\BoardTitleChanged'
            board-closed: 'Taranto\ListMaker\Domain\Model\Board\Event\BoardClosed'
            board-reopened: 'Taranto\ListMaker\Domain\Model\Board\Event\BoardReopened'
