Taranto\ListMaker\Shared\Domain\Message\DomainEvent:
    discriminator_map:
        type_property: event_type
        mapping:
            # Board
            board-created: 'Taranto\ListMaker\Board\Domain\Event\BoardCreated'
            board-title-changed: 'Taranto\ListMaker\Board\Domain\Event\BoardTitleChanged'
            board-closed: 'Taranto\ListMaker\Board\Domain\Event\BoardClosed'
            board-reopened: 'Taranto\ListMaker\Board\Domain\Event\BoardReopened'
