Taranto\ListMaker\Shared\Domain\Message\DomainEvent:
    discriminator_map:
        type_property: event_type
        mapping:
            # Board
            board-created: 'Taranto\ListMaker\Board\Domain\Event\BoardCreated'
            board-title-changed: 'Taranto\ListMaker\Board\Domain\Event\BoardTitleChanged'
            board-closed: 'Taranto\ListMaker\Board\Domain\Event\BoardClosed'
            board-reopened: 'Taranto\ListMaker\Board\Domain\Event\BoardReopened'
            # List
            list-created: 'Taranto\ListMaker\ItemList\Domain\Event\ListCreated'
            list-title-changed: 'Taranto\ListMaker\ItemList\Domain\Event\ListTitleChanged'
            list-archived: 'Taranto\ListMaker\ItemList\Domain\Event\ListArchived'
            list-restored: 'Taranto\ListMaker\ItemList\Domain\Event\ListRestored'
            list-reordered: 'Taranto\ListMaker\ItemList\Domain\Event\ListReordered'
