Taranto\ListMaker\Board\Domain\Command\CreateBoard:
    properties:
        aggregateId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            - Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\AggregateDoesNotExist:
                  idField: boardId
                  collectionName: boards
        payload:
            - Collection:
                  fields:
                      title:
                          - NotBlank: ~
                          - Length:
                                max: 50

Taranto\ListMaker\Board\Domain\Command\ChangeBoardTitle:
    properties:
        aggregateId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            - Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\AggregateExists:
                  idField: boardId
                  collectionName: boards
        payload:
            - Collection:
                  fields:
                      title:
                          - NotBlank: ~
                          - Length:
                                max: 50

Taranto\ListMaker\Board\Domain\Command\CloseBoard:
    properties:
        aggregateId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            -   Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\AggregateExists:
                  idField: boardId
                  collectionName: boards

Taranto\ListMaker\Board\Domain\Command\ReopenBoard:
    properties:
        aggregateId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            -   Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\AggregateExists:
                    idField: boardId
                    collectionName: boards
