# Commands
Taranto\ListMaker\Board\Application\Command\CreateBoard:
    properties:
        aggregateId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            - Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\MongoDocumentDoesNotExist:
                  collection: boards
        title:
            - NotBlank: ~
            - Length:
                  max: 50

Taranto\ListMaker\Board\Application\Command\ChangeBoardTitle:
    properties:
        aggregateId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            - Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\MongoDocumentExists:
                  collection: boards
                  returnsNotFoundResponse: true
        title:
            - NotBlank: ~
            - Length:
                  max: 50

Taranto\ListMaker\Board\Application\Command\CloseBoard:
    properties:
        aggregateId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            - Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\MongoDocumentExists:
                  collection: boards
                  returnsNotFoundResponse: true

Taranto\ListMaker\Board\Application\Command\ReopenBoard:
    properties:
        aggregateId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            - Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\MongoDocumentExists:
                  collection: boards
                  returnsNotFoundResponse: true

# Queries
Taranto\ListMaker\Board\Application\Query\BoardById:
    properties:
        boardId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            - Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\MongoDocumentExists:
                  collection: boards
                  returnsNotFoundResponse: true
