# Commands
Taranto\ListMaker\ItemList\Application\Command\CreateList:
    group_sequence:
        - CreateList
        - Strict
    constraints:
        - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListPosition:
              groups: [Strict]
    properties:
        aggregateId:
            - NotBlank: ~
            - Uuid:
                  versions: [4]
            - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListDoesNotExist: ~
        title:
            - NotBlank: ~
            - Length:
                  max: 50
        position:
            - Type: integer
            - GreaterThanOrEqual: 0
        boardId:
            - NotBlank: ~
            - Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\MongoDocumentExists:
                  collection: boards
                  message: 'Board not found.'

Taranto\ListMaker\ItemList\Application\Command\ChangeListTitle:
    properties:
        aggregateId:
            - NotBlank: ~
            - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListExists:
                  returnsNotFoundResponse: true
        title:
            - NotBlank: ~
            - Length:
                  max: 50

Taranto\ListMaker\ItemList\Application\Command\ArchiveList:
    properties:
        aggregateId:
            - NotBlank: ~
            - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListExists:
                  returnsNotFoundResponse: true
            - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListIsNotArchived: ~

Taranto\ListMaker\ItemList\Application\Command\RestoreList:
    properties:
        aggregateId:
            - NotBlank: ~
            - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListExists:
                  returnsNotFoundResponse: true
            - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListIsArchived: ~

Taranto\ListMaker\ItemList\Application\Command\MoveList:
    group_sequence:
        - MoveList
        - Strict
    constraints:
        - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListPosition:
              groups: [Strict]
    properties:
        aggregateId:
            - NotBlank: ~
            - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListExists:
                  returnsNotFoundResponse: true
            - Taranto\ListMaker\ItemList\Infrastructure\Validation\ListIsNotArchived:
                  message: 'Unable to move an archived list.'
        position:
            - NotBlank: ~
            - Type: integer
            - GreaterThanOrEqual: 0
        boardId:
            - NotBlank: ~
            - Taranto\ListMaker\Shared\Infrastructure\Validation\Constraints\MongoDocumentExists:
                  collection: boards
                  message: 'Board not found.'
