# Board
command::create-board:
    path: /boards
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Board\Application\Command\CreateBoard

command::change-board-title:
    path: /boards/{id}/change-title
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Board\Application\Command\ChangeBoardTitle

command::close-board:
    path: /boards/{id}/close
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Board\Application\Command\CloseBoard

command::reopen-board:
    path: /boards/{id}/reopen
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Board\Application\Command\ReopenBoard

query::closed-boards:
    path: /boards/closed
    methods: GET
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\QueryController
        _format: json
        query_class: Taranto\ListMaker\Board\Application\Query\ClosedBoards

query::open-boards:
    path: /boards
    methods: GET
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\QueryController
        _format: json
        query_class: Taranto\ListMaker\Board\Application\Query\OpenBoards

query::board-by-id:
    path: /boards/{boardId}
    methods: GET
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\QueryController
        _format: json
        query_class: Taranto\ListMaker\Board\Application\Query\BoardById

# List
command::create-list:
    path: /lists
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\ItemList\Application\Command\CreateList

command::change-list-title:
    path: /lists/{id}/change-title
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\ItemList\Application\Command\ChangeListTitle

command::archive-list:
    path: /lists/{id}/archive
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\ItemList\Application\Command\ArchiveList

command::restore-list:
    path: /lists/{id}/restore
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\ItemList\Application\Command\RestoreList

command::reorder-list:
    path: /lists/{id}/reorder
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\ItemList\Application\Command\ReorderList

command::move-list:
    path: /lists/{id}/move
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\ItemList\Application\Command\MoveList

# Item
command::add-item:
    path: /items
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Item\Application\Command\AddItem

command::change-item-title:
    path: /items/{id}/change-title
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Item\Application\Command\ChangeItemTitle

command::archive-item:
    path: /items/{id}/archive
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Item\Application\Command\ArchiveItem

command::restore-item:
    path: /items/{id}/restore
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Item\Application\Command\RestoreItem

command::change-item-description:
    path: /items/{id}/change-description
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Item\Application\Command\ChangeItemDescription

command::reorder-item:
    path: /items/{id}/reorder
    methods: POST
    defaults:
        _controller: Taranto\ListMaker\Shared\Ui\Web\Controller\CommandController
        _format: json
        command_class: Taranto\ListMaker\Item\Application\Command\ReorderItem
