board:
    prefix: /boards
    resource: routes/board.yml
    trailing_slash_on_root: false

list:
    prefix: /lists
    resource: routes/list.yml
    trailing_slash_on_root: false

item:
    prefix: /items
    resource: routes/item.yml
    trailing_slash_on_root: false
