# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Taranto\ListMaker\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Taranto\ListMaker\Ui\Web\Controller\:
        resource: '../src/Ui/Web/Controller'
        tags: ['controller.service_arguments']

    # Request Listeners
    Taranto\ListMaker\Ui\Web\EventListener\JsonRequestValidation:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    # Response Listeners
    Taranto\ListMaker\Ui\Web\EventListener\ResponseOnValidationException:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # Testing
    Taranto\ListMaker\Tests\CommandRunner: ~

    testing.database.write_model:
        class: 'Taranto\ListMaker\Tests\WriteModelDataBase'
        public: true

    testing.database.read_model:
        class: 'Taranto\ListMaker\Tests\ReadModelDataBase'
        arguments:
            - '%env(MONGO_URL)%'
            - '%env(MONGO_DATABASE)%'
        public: true
