# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $eventStore: '@Taranto\ListMaker\Shared\Infrastructure\Persistence\EventStore\MessageDispatcherEventStore'
            $boardsCollection: '@mongo.collection.boards'
            $boardsOverviewCollection: '@mongo.collection.boards_overview'
            $mongoUrl: '%env(MONGO_URL)%'
            $mongoDatabase: '%env(MONGO_DATABASE)%'
            $boardsSseUrl: 'https://cqrs-event-sourcing-example.com/boards'
            $listsSseUrl: 'https://cqrs-event-sourcing-example.com/lists'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Taranto\ListMaker\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Taranto\ListMaker\Shared\Ui\Web\Controller\:
        resource: '../src/Shared/Ui/Web/Controller'
        tags: ['controller.service_arguments']

    # Request Listeners
    Taranto\ListMaker\Shared\Ui\Web\EventListener\JsonRequestValidation:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    # Response Listeners
    Taranto\ListMaker\Shared\Ui\Web\EventListener\ResponseOnValidationException:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # Message Handlers
    command_handlers:
        namespace: Taranto\ListMaker\
        resource: '%kernel.project_dir%/src/**/Command/*Handler.php'
        tags: [{ name: messenger.message_handler, bus: command.bus }]

    query_handlers:
        namespace: Taranto\ListMaker\
        resource: '%kernel.project_dir%/src/**/Query/*Handler.php'
        tags: [{ name: messenger.message_handler, bus: query.bus }]

    projectors:
        namespace: Taranto\ListMaker\
        resource: '%kernel.project_dir%/src/**/Projection/*Projector.php'
        tags: [{ name: messenger.message_handler, bus: event.bus }]

    sse_publishers:
        namespace: Taranto\ListMaker\
        resource: '%kernel.project_dir%/src/**/SsePublisher/*Publisher.php'
        exclude: '%kernel.project_dir%/src/Shared/*'
        tags: [{ name: messenger.message_handler, bus: event.bus }]

    # Event Store
    Taranto\ListMaker\Shared\Infrastructure\Persistence\EventStore\MessageDispatcherEventStore:
        arguments:
            $eventStore: '@Taranto\ListMaker\Shared\Infrastructure\Persistence\EventStore\MySqlEventStore'
            $eventBus: '@event.bus'

    # Mongo Collections
    mongo.collection.boards:
        class: Taranto\ListMaker\Shared\Infrastructure\Persistence\Projection\MongoCollectionProvider
        factory: ['@Taranto\ListMaker\Shared\Infrastructure\Persistence\Projection\MongoCollectionProvider', 'getCollection']
        arguments: ['boards']

    # Mongo Collections
    mongo.collection.boards_overview:
        class: Taranto\ListMaker\Shared\Infrastructure\Persistence\Projection\MongoCollectionProvider
        factory: ['@Taranto\ListMaker\Shared\Infrastructure\Persistence\Projection\MongoCollectionProvider', 'getCollection']
        arguments: ['boards_overview']

    # Serializer
    Symfony\Component\Serializer\Normalizer\PropertyNormalizer: ~
